version: '3.8'

services:
  django:
    container_name: django_dockerize
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" ##host:container
    env_file:
      - .env
    command: python3 manage.py runserver 0:8000
    